### ISSUE TITLE
css is not doing what I expected

### ISSUE THREAD

**Issue by Riv67** [Riv67/header-icons#1]
I’m not even sure what exactly to ask... I’ve been trying to follow the “flexing your muscles” page as a guide and using cheat sheets. Lots of trial and error and refreshing the webpage, but it’s still not doing what I want and I’m not sure how to fix it. I think maybe I’m not targeting the html correctly?? I’m also confused because some things do show up when I refresh (font-size and colour of header) but other tags just don’t change anything (list-style-type, font-family, colour of links,) I don’t know what i’m doing wrong. I’ve left those tags in the css, maybe you can see the problem? This is currently what my page looks like:
![Screenshot 2019-11-01 10 20 14](https://user-images.githubusercontent.com/55094177/68031576-5865c480-fc92-11e9-8528-b68725006588.png)

Also, how can I target the images? Do I have to add something in the html? 
Thx!
@thomasjbradley

**Comment by thomasjbradley** [comment]
Everything seems to be working okay to me.

I would suggest a small change in the HTML to make it easier to create the layout:
Wrap the images & the `<h1>` in a `<div>` tag.
https://github.com/Riv67/header-icons/blob/gh-pages/index.html#L12-L14
Then add `display: flex` to the div instead of on `header`

**Comment by Riv67** [comment]
Okay.
Still not sure why the font isn’t the same as the screenshot, and why the links have bullets and aren’t white. Is my css wrong for the .links section?

I’ll start by making those changes to the html, thanks!

**Comment by thomasjbradley** [comment]
The CSS for the links isn’t specific enough—it’s targeting the `<nav>` but the `<a>` tags need to be targeted to change the colour. For the bullets, it’s similar, `.link` is a `<nav>` tag, which doesn’t have bullets to be removed, the `<ul>` has the bullets.

**Comment by Riv67** [comment]
Ok, that makes sense, thank you.
